script:
  - "npm run travis"

language: node_js

node_js:
  - "4"
  - "6"
  - "8"
  - "9"

branches:
  except:
    - /^v\d+\./

matrix:
  fast_finish: true
  include:
    - node_js: "4"
      env: COVERAGE=true
  allow_failures:
    - env: COVERAGE=true

sudo: false
